import type { Metadata } from "next";
import { Albert_Sans, Baloo_2 } from "next/font/google";
import "./globals.css";

import { styleSheet } from "~/css";

const albertSans = Albert_Sans({
  variable: "--font-albert-sans",
  subsets: ["latin"],
  weight: ["400", "500"]
});

const baloo2 = Baloo_2({
  variable: "--font-baloo-2",
  subsets: ["latin"],
  weight: ["400"]
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <style dangerouslySetInnerHTML={{ __html: styleSheet() }} />
      </head>
      <body className={`${albertSans.variable} ${baloo2.variable}`}>
        <main>
          {children}
        </main>
      </body>
    </html>
  );
}
